<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="abstracta" nsURI="abstracta" nsPrefix="abstracta">
  <eAnnotations source="gmf"/>
  <eClassifiers xsi:type="ecore:EClass" name="TcdPaquete">
    <eStructuralFeatures xsi:type="ecore:EReference" name="listaClases" upperBound="-1"
        eType="#//TcdClase" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="listapaquetes" upperBound="-1"
        eType="#//TcdPaquete" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nombre" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ruta" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TcdClase">
    <eStructuralFeatures xsi:type="ecore:EReference" name="listaAtributos" upperBound="-1"
        eType="#//TcdAtributo" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="listaMetodos" upperBound="-1"
        eType="#//TcdMetodo" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="listaRelaciones" upperBound="-1"
        eType="#//TcdRelacion" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nombre" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="estereotipo" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="modificadorAcceso" eType="#//Visibilidad"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isAbstract" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="documentacion" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TcdAtributo">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nombre" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="tipoDato" eType="#//TipoDato"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="visibilidad" eType="#//Visibilidad"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isConstante" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isStatic" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="valorDefecto" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TcdMetodo">
    <eStructuralFeatures xsi:type="ecore:EReference" name="listaParametros" upperBound="-1"
        eType="#//TcdParametro" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nombre" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="modificadorAcceso" eType="#//Visibilidad"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="tipoRetorno" eType="#//TipoRetorno"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="semantica" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TcdRelacion" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" eType="#//TcdClase"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="#//TcdClase"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="navegavilidad" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TcdAsociacion" eSuperTypes="#//TcdRelacion">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nombreOrigen" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nombreDestino" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="multiplicidadOrigen" eType="#//Multiplicidad"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="multiplicidadDestino" eType="#//Multiplicidad"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TcdComposicion" eSuperTypes="#//TcdRelacion">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nombreOrigen" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nombreDestino" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="multiplicidadOrigen" eType="#//Multiplicidad"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="multiplicidadDestino" eType="#//Multiplicidad"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TcdDependencia" eSuperTypes="#//TcdRelacion">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nombreOrigen" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nombreDestino" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="multiplicidadOrigen" eType="#//Multiplicidad"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="multiplicidadDestino" eType="#//Multiplicidad"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TcdHerencia" eSuperTypes="#//TcdRelacion"/>
  <eClassifiers xsi:type="ecore:EClass" name="TcdAgregacion" eSuperTypes="#//TcdRelacion">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nombreOrigen" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nombreDestino" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="multiplicidadOrigen" eType="#//Multiplicidad"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="multiplicidadDestino" eType="#//Multiplicidad"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TcdParametro">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nombre" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="tipoDato" eType="#//TipoDato"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Visibilidad">
    <eLiterals name="public"/>
    <eLiterals name="private" value="1"/>
    <eLiterals name="protected" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="TipoDato">
    <eLiterals name="string"/>
    <eLiterals name="number" value="1"/>
    <eLiterals name="boolean" value="2"/>
    <eLiterals name="undefined" value="3"/>
    <eLiterals name="null" value="4"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Multiplicidad">
    <eLiterals name="uno"/>
    <eLiterals name="uno_cero" value="1"/>
    <eLiterals name="cero_varios" value="2"/>
    <eLiterals name="uno_varios" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="TipoRetorno">
    <eLiterals name="string"/>
    <eLiterals name="number" value="1"/>
    <eLiterals name="boolean" value="2"/>
    <eLiterals name="undefined" value="3"/>
  </eClassifiers>
</ecore:EPackage>
