<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="abstracta" nsURI="abstracta" nsPrefix="abstracta">
  <eAnnotations source="gmf"/>
  <eClassifiers xsi:type="ecore:EClass" name="ModelFactory">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nombre" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ruta" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="listaPaquetes" upperBound="-1"
        eType="#//TCDPaquete" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="listaTodasClases" upperBound="-1"
        eType="#//TCDClase"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="listaTodosPaquetes" upperBound="-1"
        eType="#//TCDPaquete"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TCDPaquete">
    <eStructuralFeatures xsi:type="ecore:EReference" name="listaClases" upperBound="-1"
        eType="#//TCDClase" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="listapaquetes" upperBound="-1"
        eType="#//TCDPaquete" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nombre" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ruta" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TCDClase">
    <eStructuralFeatures xsi:type="ecore:EReference" name="listaAtributos" upperBound="-1"
        eType="#//TCDAtributo" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="listaMetodos" upperBound="-1"
        eType="#//TCDMetodo" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="listaRelaciones" upperBound="-1"
        eType="#//TCDRelacion" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nombre" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="estereotipo" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isAbstract" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="documentacion" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ruta" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TCDAtributo">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nombre" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="tipoDato" eType="#//TipoDato"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="visibilidad" eType="#//Visibilidad"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="valorDefecto" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TCDMetodo">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="listaParametros" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nombre" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="modificadorAcceso" eType="#//Visibilidad"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="tipoRetorno" eType="#//TipoRetorno"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="semantica" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TCDRelacion" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" eType="#//TCDClase"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="#//TCDClase"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TCDAsociacion" eSuperTypes="#//TCDRelacion">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nombreOrigen" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nombreDestino" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="multiplicidadOrigen" eType="#//Multiplicidad"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="multiplicidadDestino" eType="#//Multiplicidad"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="navegavilidad" eType="#//Navegavilidad"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TCDComposicion" eSuperTypes="#//TCDRelacion">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nombreOrigen" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nombreDestino" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="multiplicidadOrigen" eType="#//Multiplicidad"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="multiplicidadDestino" eType="#//Multiplicidad"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TCDDependencia" eSuperTypes="#//TCDRelacion">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nombreOrigen" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nombreDestino" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="multiplicidadOrigen" eType="#//Multiplicidad"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="multiplicidadDestino" eType="#//Multiplicidad"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TCDHerencia" eSuperTypes="#//TCDRelacion"/>
  <eClassifiers xsi:type="ecore:EClass" name="TCDAgregacion" eSuperTypes="#//TCDRelacion">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nombreOrigen" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nombreDestino" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="multiplicidadOrigen" eType="#//Multiplicidad"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="multiplicidadDestino" eType="#//Multiplicidad"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TCDParametro">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nombre" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="tipoDato" eType="#//TipoDato"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Visibilidad">
    <eLiterals name="Public"/>
    <eLiterals name="Private" value="1"/>
    <eLiterals name="Protected" value="2"/>
    <eLiterals name="Readonly" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="TipoDato">
    <eLiterals name="any"/>
    <eLiterals name="string" value="1"/>
    <eLiterals name="number" value="2"/>
    <eLiterals name="boolean" value="3"/>
    <eLiterals name="undefined" value="4"/>
    <eLiterals name="null" value="5"/>
    <eLiterals name="Void" value="6"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Multiplicidad">
    <eLiterals name="_1"/>
    <eLiterals name="_0_1" value="1"/>
    <eLiterals name="_0_n" value="2"/>
    <eLiterals name="_1_n" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="TipoRetorno">
    <eLiterals name="undefined"/>
    <eLiterals name="string" value="1"/>
    <eLiterals name="number" value="2"/>
    <eLiterals name="boolean" value="3"/>
    <eLiterals name="Void" value="4"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Navegavilidad">
    <eLiterals name="Bidireccional"/>
    <eLiterals name="Unidireccional" value="1"/>
    <eLiterals name="None" value="2"/>
  </eClassifiers>
</ecore:EPackage>
