/**
 */
package abstracta.provider;

import abstracta.util.AbstractaAdapterFactory;

import java.util.ArrayList;
import java.util.Collection;

import org.eclipse.emf.common.notify.Adapter;
import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.Notifier;

import org.eclipse.emf.edit.provider.ChangeNotifier;
import org.eclipse.emf.edit.provider.ComposeableAdapterFactory;
import org.eclipse.emf.edit.provider.ComposedAdapterFactory;
import org.eclipse.emf.edit.provider.IChangeNotifier;
import org.eclipse.emf.edit.provider.IDisposable;
import org.eclipse.emf.edit.provider.IEditingDomainItemProvider;
import org.eclipse.emf.edit.provider.IItemLabelProvider;
import org.eclipse.emf.edit.provider.IItemPropertySource;
import org.eclipse.emf.edit.provider.INotifyChangedListener;
import org.eclipse.emf.edit.provider.IStructuredItemContentProvider;
import org.eclipse.emf.edit.provider.ITreeItemContentProvider;

/**
 * This is the factory that is used to provide the interfaces needed to support Viewers.
 * The adapters generated by this factory convert EMF adapter notifications into calls to {@link #fireNotifyChanged fireNotifyChanged}.
 * The adapters also support Eclipse property sheets.
 * Note that most of the adapters are shared among multiple instances.
 * <!-- begin-user-doc -->
 * <!-- end-user-doc -->
 * @generated
 */
public class AbstractaItemProviderAdapterFactory extends AbstractaAdapterFactory implements ComposeableAdapterFactory, IChangeNotifier, IDisposable {
	/**
	 * This keeps track of the root adapter factory that delegates to this adapter factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ComposedAdapterFactory parentAdapterFactory;

	/**
	 * This is used to implement {@link org.eclipse.emf.edit.provider.IChangeNotifier}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IChangeNotifier changeNotifier = new ChangeNotifier();

	/**
	 * This keeps track of all the supported types checked by {@link #isFactoryForType isFactoryForType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Collection<Object> supportedTypes = new ArrayList<Object>();

	/**
	 * This constructs an instance.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public AbstractaItemProviderAdapterFactory() {
		supportedTypes.add(IEditingDomainItemProvider.class);
		supportedTypes.add(IStructuredItemContentProvider.class);
		supportedTypes.add(ITreeItemContentProvider.class);
		supportedTypes.add(IItemLabelProvider.class);
		supportedTypes.add(IItemPropertySource.class);
	}

	/**
	 * This keeps track of the one adapter used for all {@link abstracta.ModelFactory} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ModelFactoryItemProvider modelFactoryItemProvider;

	/**
	 * This creates an adapter for a {@link abstracta.ModelFactory}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createModelFactoryAdapter() {
		if (modelFactoryItemProvider == null) {
			modelFactoryItemProvider = new ModelFactoryItemProvider(this);
		}

		return modelFactoryItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link abstracta.TCDPaquete} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TCDPaqueteItemProvider tcdPaqueteItemProvider;

	/**
	 * This creates an adapter for a {@link abstracta.TCDPaquete}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTCDPaqueteAdapter() {
		if (tcdPaqueteItemProvider == null) {
			tcdPaqueteItemProvider = new TCDPaqueteItemProvider(this);
		}

		return tcdPaqueteItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link abstracta.TCDClase} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TCDClaseItemProvider tcdClaseItemProvider;

	/**
	 * This creates an adapter for a {@link abstracta.TCDClase}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTCDClaseAdapter() {
		if (tcdClaseItemProvider == null) {
			tcdClaseItemProvider = new TCDClaseItemProvider(this);
		}

		return tcdClaseItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link abstracta.TCDAtributo} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TCDAtributoItemProvider tcdAtributoItemProvider;

	/**
	 * This creates an adapter for a {@link abstracta.TCDAtributo}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTCDAtributoAdapter() {
		if (tcdAtributoItemProvider == null) {
			tcdAtributoItemProvider = new TCDAtributoItemProvider(this);
		}

		return tcdAtributoItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link abstracta.TCDClass_identifier} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TCDClass_identifierItemProvider tcdClass_identifierItemProvider;

	/**
	 * This creates an adapter for a {@link abstracta.TCDClass_identifier}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTCDClass_identifierAdapter() {
		if (tcdClass_identifierItemProvider == null) {
			tcdClass_identifierItemProvider = new TCDClass_identifierItemProvider(this);
		}

		return tcdClass_identifierItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link abstracta.TCDMetodo} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TCDMetodoItemProvider tcdMetodoItemProvider;

	/**
	 * This creates an adapter for a {@link abstracta.TCDMetodo}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTCDMetodoAdapter() {
		if (tcdMetodoItemProvider == null) {
			tcdMetodoItemProvider = new TCDMetodoItemProvider(this);
		}

		return tcdMetodoItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link abstracta.TCDAsociacion} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TCDAsociacionItemProvider tcdAsociacionItemProvider;

	/**
	 * This creates an adapter for a {@link abstracta.TCDAsociacion}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTCDAsociacionAdapter() {
		if (tcdAsociacionItemProvider == null) {
			tcdAsociacionItemProvider = new TCDAsociacionItemProvider(this);
		}

		return tcdAsociacionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link abstracta.TCDComposicion} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TCDComposicionItemProvider tcdComposicionItemProvider;

	/**
	 * This creates an adapter for a {@link abstracta.TCDComposicion}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTCDComposicionAdapter() {
		if (tcdComposicionItemProvider == null) {
			tcdComposicionItemProvider = new TCDComposicionItemProvider(this);
		}

		return tcdComposicionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link abstracta.TCDDependencia} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TCDDependenciaItemProvider tcdDependenciaItemProvider;

	/**
	 * This creates an adapter for a {@link abstracta.TCDDependencia}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTCDDependenciaAdapter() {
		if (tcdDependenciaItemProvider == null) {
			tcdDependenciaItemProvider = new TCDDependenciaItemProvider(this);
		}

		return tcdDependenciaItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link abstracta.TCDHerencia} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TCDHerenciaItemProvider tcdHerenciaItemProvider;

	/**
	 * This creates an adapter for a {@link abstracta.TCDHerencia}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTCDHerenciaAdapter() {
		if (tcdHerenciaItemProvider == null) {
			tcdHerenciaItemProvider = new TCDHerenciaItemProvider(this);
		}

		return tcdHerenciaItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link abstracta.TCDAgregacion} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TCDAgregacionItemProvider tcdAgregacionItemProvider;

	/**
	 * This creates an adapter for a {@link abstracta.TCDAgregacion}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTCDAgregacionAdapter() {
		if (tcdAgregacionItemProvider == null) {
			tcdAgregacionItemProvider = new TCDAgregacionItemProvider(this);
		}

		return tcdAgregacionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link abstracta.TCDParametro} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TCDParametroItemProvider tcdParametroItemProvider;

	/**
	 * This creates an adapter for a {@link abstracta.TCDParametro}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTCDParametroAdapter() {
		if (tcdParametroItemProvider == null) {
			tcdParametroItemProvider = new TCDParametroItemProvider(this);
		}

		return tcdParametroItemProvider;
	}

	/**
	 * This returns the root adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public ComposeableAdapterFactory getRootAdapterFactory() {
		return parentAdapterFactory == null ? this : parentAdapterFactory.getRootAdapterFactory();
	}

	/**
	 * This sets the composed adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void setParentAdapterFactory(ComposedAdapterFactory parentAdapterFactory) {
		this.parentAdapterFactory = parentAdapterFactory;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public boolean isFactoryForType(Object type) {
		return supportedTypes.contains(type) || super.isFactoryForType(type);
	}

	/**
	 * This implementation substitutes the factory itself as the key for the adapter.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter adapt(Notifier notifier, Object type) {
		return super.adapt(notifier, this);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Object adapt(Object object, Object type) {
		if (isFactoryForType(type)) {
			Object adapter = super.adapt(object, type);
			if (!(type instanceof Class<?>) || (((Class<?>)type).isInstance(adapter))) {
				return adapter;
			}
		}

		return null;
	}

	/**
	 * This adds a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void addListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.addListener(notifyChangedListener);
	}

	/**
	 * This removes a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void removeListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.removeListener(notifyChangedListener);
	}

	/**
	 * This delegates to {@link #changeNotifier} and to {@link #parentAdapterFactory}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void fireNotifyChanged(Notification notification) {
		changeNotifier.fireNotifyChanged(notification);

		if (parentAdapterFactory != null) {
			parentAdapterFactory.fireNotifyChanged(notification);
		}
	}

	/**
	 * This disposes all of the item providers created by this factory. 
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void dispose() {
		if (modelFactoryItemProvider != null) modelFactoryItemProvider.dispose();
		if (tcdPaqueteItemProvider != null) tcdPaqueteItemProvider.dispose();
		if (tcdClaseItemProvider != null) tcdClaseItemProvider.dispose();
		if (tcdAtributoItemProvider != null) tcdAtributoItemProvider.dispose();
		if (tcdClass_identifierItemProvider != null) tcdClass_identifierItemProvider.dispose();
		if (tcdMetodoItemProvider != null) tcdMetodoItemProvider.dispose();
		if (tcdAsociacionItemProvider != null) tcdAsociacionItemProvider.dispose();
		if (tcdComposicionItemProvider != null) tcdComposicionItemProvider.dispose();
		if (tcdDependenciaItemProvider != null) tcdDependenciaItemProvider.dispose();
		if (tcdHerenciaItemProvider != null) tcdHerenciaItemProvider.dispose();
		if (tcdAgregacionItemProvider != null) tcdAgregacionItemProvider.dispose();
		if (tcdParametroItemProvider != null) tcdParametroItemProvider.dispose();
	}

}
